#
# Common configuration for all devices.
#

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

# WiFi multi network
wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid_2
    password: !secret wifi_password_2
  - ssid: !secret wifi_ssid_3
    password: !secret wifi_password_3

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${nombre} Fallback Hotspot"
    password: !secret fallback_ap_password

captive_portal:

logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

preferences:
  flash_write_interval: 60min

# Enable OTA updates
ota:
  password: !secret ota_password

# Common sensors
sensor:
  - name: Uptime
    platform: uptime
    update_interval: 120s

  - name: Wifi Signal
    platform: wifi_signal
    update_interval: 120s

text_sensor:
  - name: Version
    platform: version
    hide_timestamp: True

# Restart button
button:
  - name: Restart
    platform: restart
