#
# Common configuration for all devices.
#

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

# WiFi multi network
wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid_2
    password: !secret wifi_password_2
  - ssid: !secret wifi_ssid_3
    password: !secret wifi_password_3
  - ssid: !secret wifi_ssid_4
    password: !secret wifi_password_4

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: !secret fallback_ap_password

# No se si todos los dispositivos lo soportan (sonoff?)
#network:
#    enable_ipv6: true

captive_portal:

logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

preferences:
  flash_write_interval: 60min

# Enable OTA updates
ota:
  password: !secret ota_password

# Web Server
web_server:

# Pruebo MQTT, primero plain text, luego tls
# Pasar a base.yaml
mqtt:
  broker: 10.1.1.8
  username: esphome
  password: !secret mqtt_password_esphome
  topic_prefix: esphome/${device_name}
  log_topic: null # La salida de esto es interesante para analizar pero en el uso normal molesta

# Common sensors
sensor:
  - name: Uptime
    platform: uptime
    update_interval: 120s
  - name: Wifi Signal
    platform: wifi_signal
    update_interval: 120s

text_sensor:
  - name: Version
    platform: version
    hide_timestamp: True
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      address_0:
        name: ESP IP Address 0
      address_1:
        name: ESP IP Address 1
      address_2:
        name: ESP IP Address 2
#      address_3:
#        name: ESP IP Address 3
#      address_4:
#        name: ESP IP Address 4
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results
    dns_address:
      name: ESP DNS Address

# Restart button
#button:
#  - name: Restart
#    platform: restart
